#!/bin/bash

#SBATCH --job-name=Dmel_fanc
#SBATCH --partition=basic
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --output=nuc-%j.out
#SBATCH --error=nuc-%j.err
#SBATCH --time=00:20:00

module load Fan-C/0.9.28-foss-2023b

matrix=$1
out=$2
chr=$3

fanc from-txt /scratch/molevo/Dmel/Hi-C/EMB-hic/male/rawdata.out/hic_results.v2/matrix/male_16-18h.emb_sample1/iced/25000/male_16-18h.emb_sample1_25000_iced.matrix /scratch/molevo/Dmel/Hi-C/EMB-hic/male/rawdata.out/hic_results.v2/matrix/male_16-18h.emb_sample1/raw/25000/male_16-18h.emb_sample1_25000_abs.bed Dmelchrfa_EmbM_sample1_hicpro_25k.hic

fanc subset $matrix $out $chr

fanc compartments -e $out.X.pdf $matrix $out.X.ab -s 0 -p 10 20 30 40 50 60 70 80 90 100 -g ../bowtie2_index/Dmel.chr.fa -x 2L 2R 3L 3R --compartment-strength $out.strength.X.txt -f -v $out.ev.X.txt --recalculate
